#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 17 12:36:19 2018

@author: Aidan
"""
import operator
from bs4 import BeautifulSoup
from urllib.request import urlopen

#Finds the vote history page of a given bill
with urlopen('https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201720180AB245') as homepage:
    soup = BeautifulSoup(homepage.read(), 'html.parser')

#Determines which rep we are searching for
#representative=input('Enter last name:')


# Finds all the aye votes in the last vote
ayes = soup.find('span', {'title': 'Ayes'}).next_element.next_element.next_element.next_element

#Finds all the nay votes in the last vote
noes = soup.find('span', {'title': 'Noes'}).next_element.next_element.next_element.next_element

#Finds all the missing votes in the last vote
novotes = soup.find('span', {'title': 'No Votes Recorded'}).next_element.next_element.next_element.next_element

#Proves the program finds the right element
#print(ayes)

#Proves the program finds the right element
#print(noes)

#Proves the program finds the right element
#print(novotes)

#Searches aye votes for given rep, if present the program states they voted yes
repvotedyes= (operator.contains(ayes, 'Cunningham'))
if (repvotedyes == True):
    print('Rep voted for this bill')

#Searches no votes for given rep, if present the program states they voted no
repvotedno= (operator.contains(noes, 'Cunningham'))
if (repvotedno == True):
    print('Rep voted against this bill')

#Searches missing votes for given rep, if present states they did not vote
repdidnotvote= (operator.contains(novotes, 'Cunningham'))
if (repdidnotvote == True):
    print('Rep did not vote for this bill')